# cloith-platform Cluster Configuration for single node k3s-ngf-1cluster-1node set-up
token: "your-very-secure-secret-token"
cluster-name: "cloith-platform"
disable:
  - traefik     # We use NGF instead
  - servicelb   # Lightens the load
write-kubeconfig-mode: "644"
node-label:
  - "env=production"
  - "platform=cloith"