apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: mqtt-infra
data:
  mosquitto.conf: |
    # Raw MQTT
    # listener 1883 0.0.0.0
    # allow_anonymous true

    # MQTT over WebSockets
    listener 9001 0.0.0.0
    protocol websockets
    allow_anonymous true
